export const apiTags = {
  currencies: 'currencies',
  auth: 'auth',
  orders: 'orders',
  users: 'users',
  notifications: 'notifications',
  dashboard: 'dashboard',
  wallet: 'wallet',
  transaction: 'transaction',
  account: 'account',
  admin: 'admin',
  kyc: 'kyc',
  webhook: 'webhook',
  card: 'cards',
  adminUsers: 'admin/users',
  adminTransactions: 'admin/transactions',
  rate: 'rate',
  internalUser: 'admin/internal-users',
  internalRole: 'admin/internal-roles',
  fiat: 'admin/fiat',
  cryptoBuffer: 'admin/crypto',
  cryptoCurrencyRate: 'admin/currency/interest-rates',
  urgentLiquidity: 'admin/urgent-liquidity',
  autoStacking: 'admin/auto-stacking',
  adminLiquidity: 'admin/liquidity',
  vault: 'vaults',
  settings: 'settings',
};
